sudo: required

language: node_js

node_js:
  - '6'

env:
  NODE_ENV: 'test'

before_script:
  - sudo apt-get install graphicsmagick
  - npm install -g mocha

notifications:
  email:
    - alberto@linkysystems.com
